import { Meta, StoryObj } from '@storybook/react';
import { MediaPlayer } from './MediaPlayer';
declare const meta: Meta<typeof MediaPlayer>;
export default meta;
type Story = StoryObj<typeof MediaPlayer>;
export declare const Default: Story;
export declare const WithShakaControls: Story;
export declare const AutoplayMuted: Story;
export declare const DebugMode: Story;
export declare const DarkTheme: Story;
