import { Meta, StoryObj } from '@storybook/react-vite';
import { default as BarChart } from './BarChart';
declare const meta: Meta<typeof BarChart>;
export default meta;
type Story = StoryObj<typeof meta>;
export declare const Simple: Story;
export declare const MultipleSeries: Story;
export declare const Stacked: Story;
export declare const LargeNumbers: Story;
export declare const NegativeValues: Story;
export declare const ComplexData: Story;
export declare const Horizontal: Story;
